# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
zh:
  languageCode: zh-Hans
  contentDir: content/zh
  title: 刘志航
  params:
    description: Site description in Chinese...
  main:
  - name: 首页
    url: '#about'
    weight: 10
  - name: 文章
    url: '#posts'
    weight: 20
  - name: 项目
    url: '#projects'
    weight: 30
  - name: 演讲
    url: '#talks'
    weight: 40
  - name: 出版物
    url: '#featured'
    weight: 50
  - name: 联系我
    url: '#contact'
    weight: 60
